"""empty message

Revision ID: 2fd21fcd83e8
Revises: 
Create Date: 2022-04-28 16:56:01.458165

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2fd21fcd83e8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('manufacturer_country', postgresql.UUID(), nullable=True))
    op.add_column('product', sa.Column('type', postgresql.UUID(), nullable=True))
    op.add_column('product', sa.Column('brand', postgresql.UUID(), nullable=True))
    op.create_foreign_key(None, 'product', 'country', ['manufacturer_country'], ['id'])
    op.create_foreign_key(None, 'product', 'brand', ['brand'], ['id'])
    op.create_foreign_key(None, 'product', 'type', ['type'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_column('product', 'brand')
    op.drop_column('product', 'type')
    op.drop_column('product', 'manufacturer_country')
    # ### end Alembic commands ###
